<?php
// echo '<pre>';
// print_r($block->getData('result_by_ticket_id'));
$history = $block->getData('history_by_ticket_id');
$result = $block->getData('result_by_ticket_id');
$customerdata= $block->getCustomerData();
$custField ='';
$customclass='';
$canReopen = false;
$forAction=2;
$custId=0;
$label='Close Ticket';

if ($customerdata->isLoggedIn()) {
    // echo '<pre>';
    $custEmail=$customerdata->getCustomer()->getEmail();
    $custId=$customerdata->getCustomer()->getId();
    $custField = '<input type="hidden" name="customer-id" value="'.$custId.'">';
}
if ($result[0]['status']==0) {
    $status = '<span style="color:#C31919">Open</span>';
} elseif ($result[0]['status']==1) {
    $status = '<span style="color:#ea8600">In Process</span>';
} elseif ($result[0]['status']==2) {
    $customclass='deactive-form';
    $canReope=true;
    $forAction=0;
    $label = 'Re-Open Ticket';
    $status = '<span style="color:#0DA513">Closed</span>';
}
?>
<div class="supporting-conversation-main">
    <div class="supporting-conversation-head">
        <div class="supporting-conversation-left">
            <ul>
                <li>Ticket key: <?= /* @noEscape */ $result[0]['ticket_key'] ?></li>
                <li>Created on: <?= /* @noEscape */ $result[0]['created_at'] ?></li>
                <li>Subject: <?= /* @noEscape */ $result[0]['subject'] ?></li>
            </ul>
        </div>
        <div class="supporting-conversation-right">
            <a href="<?= /* @noEscape */ $block->getbaseurl();?>/support/index/index">View All Tickets</a>
            <form method='post' action='<?= /* @noEscape */ $block->getbaseurl();?>/support/index/submit' >
                <input type="hidden" name="form-type" value="actionform">
                <input type="hidden" name="ticket_id" value="<?= /* @noEscape */ $result[0]['ticket_id'] ?>">
                <input type="hidden" name="status" value="<?= /* @noEscape */ $forAction ?>">
                <input type="hidden" name="customer-id" value="<?= /* @noEscape */ $custId ?>">
                <input type="hidden" name="customer-email" value="<?= /* @noEscape */ $custEmail ?>">
                <input type="submit" name="submit" class="raise_ticket support-btn" 
                value="<?= /* @noEscape */ $label ?>">
            </form>
            <div class="supporting-conversation-status">Status: <span><?= /* @noEscape */ $status ?></span></div>
        </div>
    </div>
    <div class="supporting-conversation-content">
        <div class="supporting-conversation-detail">
            <?php
                $filecontainer='';
                $customerHtml='';
                $agentHtml='';
            foreach ($history as $k => $v) {
                if ($history[$k]['responder_id']==0) {
                    if (!empty($history[$k]['attachment'])) {
                        $filecontainer = '<a href='.$block->getbaseurl().$history[$k]['attachment'].' 
                        target="_blank">See attachment</a>';
                    }
                    $agentHtml .= '<div class="sender">
                                            <div class="sender-iner">
                                                <div class="conversation-info">
                                                    <span class="messager-name">Agent</span>
                                                    <span class="messager-time">'.$history[$k]['created_at'].'</span>
                                                </div>    
                                                <p>'.$history[$k]['body'].'</p>'.$filecontainer.'
                                            </div>
                                        </div>';
                } else {
                    $customerdata = $block->getCustomerDataById($history[$k]['responder_id']);
                    $customerName = $customerdata->getFirstName().' '.$customerdata->getLastName();
                    $email = $customerdata->getEmail();
                    if (!empty($history[$k]['attachment'])) {
                        $filecontainer = '<a href='.$block->getbaseurl().$history[$k]['attachment'].' 
                                            target="_blank">See attachment</a>';
                    }
                    $agentHtml .= '<div class="reciever">
                                            <div class="reciever-iner">
                                                <div class="conversation-info">
                                                    <span class="messager-name">You</span>
                                                    <span class="messager-time">'.$history[$k]['created_at'].'</span>
                                                </div>    
                                                <p>'.$history[$k]['body'].'</p>'.$filecontainer.'
                                            </div>
                                        </div>';
                }
                $filecontainer ='';
            }
                // echo $customerHtml;
                // @codingStandardsIgnoreStart
                echo $agentHtml;
                // @codingStandardsIgnoreEnd
            ?> 
            
        </div>
        <div class="supporting-conversation-tools">
            <form action='<?= /* @noEscape */ $block->getbaseurl().'support/index/submit'?>' 
            enctype="multipart/form-data" method='post' class='<?= /* @noEscape */ $customclass ?>'>
                <input type="hidden" name="form-type" value="chatbox">
                <input type='hidden' name='customer_name' value='<?= /* @noEscape */ $customerName ?>'>
                <input type='hidden' name='customer_email' value='<?= /* @noEscape */ $custEmail ?>'>
                <input type="hidden" name="ticket_id" value="<?= /* @noEscape */ $result[0]['ticket_id'] ?>">
                <input type="hidden" name="status" value="<?= /* @noEscape */ $result[0]['status'] ?>">
                <input type="hidden" name="sub" value="<?= /* @noEscape */ $result[0]['subject'] ?>">
                <input type="hidden" name="severity" value="<?= /* @noEscape */ $result[0]['severity'] ?>">
                <?= /* @noEscape */ $custField;?>
                <textarea name="customer_query" placeholder="Type a message" id="" cols="30" rows="1" required="required"></textarea>
                <div class="supporting-conversation-tools-buttons">
                    <input type="file" name="attachment" id="">
                    <input type="submit" name="submit" class="raise_ticket support-btn" value="Send">
                </div>
            </form>
        </div>
    </div>
</div>